name: MacosFunMachine

on:
  workflow_dispatch:
      inputs:
        acc:
          default: '0'
  push:
      
jobs:
  Parse:
    runs-on: macos-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip3 install undetected-chromedriver
    - name: Parser
      run: python script.py ${{inputs.acc}}
